### ISSUE TITLE
App crash when clear input field row and col

### ISSUE THREAD

**Issue by hoaxvo16** [vitconkue/tic-tac-toe-custom-react#1]
- Clear field in row and col input cause to "" value in event handle and can't parse to int = > got NaN pleased fix by checking isNaN(value)

**Comment by vitconkue** [comment]
@hoaxvo16 thank you, I will add a fallback value for col and row

**Comment by vitconkue** [comment]
5b542dd823316c66ceb8a410702b9b5572c6df5d

Now if the input is empty, it falls back to default: 3
